# Generated by Django 3.1.5 on 2021-02-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Text_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
